`\typeof` construct, set variables
kframework/matching-logic-prover pull request #60
Opened 2020-04-21 12:54 UTC by h0nzZik

2020-04-21 15:53 UTC, nishantjr commented
This looks good. Can you add a few test cases (perhaps just for the new cases) for `#syntacticMatch`.
Last commit message should be something more descriptive perhaps: "kore: add cases for \typeof for various meta functions"

2020-04-21 15:59 UTC, nishantjr requested changes

2020-04-21 15:59 UTC, nishantjr commented on prover/lang/kore-lang.md
> +    => getFreeVariables(P)
Why do we assume that the RHS of typeof has no free variables? Most likely it *is* just a symbol, but there's no reason for this rule to make that an assumption

2020-04-21 15:59 UTC, nishantjr commented on prover/lang/kore-lang.md
> +  rule alphaRename(\typeof(P, S)) => \typeof(alphaRename(P), S)
Same here

2020-04-21 15:59 UTC, nishantjr commented on prover/lang/kore-lang.md
> +  rule alphaRename(\typeof(P, S)) => \typeof(alphaRename(P), S)
Same here

2020-04-21 16:10 UTC, nishantjr commented
This looks good. Can you add a few test cases (perhaps just for the new cases) for `#syntacticMatch`.
Last commit message should be something more descriptive perhaps: "kore: add cases for \typeof for various meta functions"

I guess in the long run, `alphaRename`, `subst`, `hasImplicationContext` etc should all be implemented as visitors?

2020-04-21 16:34 UTC, nishantjr commented
This looks good. Can you add a few test cases (perhaps just for the new cases) for `#syntacticMatch`.
Last commit message should be something more descriptive perhaps: "kore: add cases for \typeof for various meta functions"

I guess in the long run, `alphaRename`, `subst`, `hasImplicationContext` etc should all be implemented as visitors?

2020-04-22 03:05 UTC, nishantjr commented on prover/lang/kore-lang.md
> +    => hasImplicationContext(P)
ditto

2020-04-22 12:53 UTC, h0nzZik commented on prover/lang/kore-lang.md
> +    => getFreeVariables(P)
Because it is declared as `"\\typeof" "(" Pattern "," Sort ")"`; the second parameter is not a pattern, but a sort. The same for the other comments.

2020-04-24 01:23 UTC, nishantjr commented
Looks good!

2020-04-24 13:06 UTC, merged